version: '3'
services:
  web:
    container_name: docker-node-mysql
    image: bookings
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mysql-fec
  mysql-fec:
    container_name: mysql-fec
    image: mysql/mysql-server:5.7.23
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: availability
      MYSQL_USER: student
      MYSQL_PASSWORD: student
